on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo:
          - ibm-garage-cloud/ibm-garage-iteration-zero
          - ibm-garage-cloud/garage-terraform-modules

    steps:
      - name: Repository dispatch ${{ matrix.repo }}
        uses: ibm-garage-cloud/action-repository-dispatch@main
        with:
          notifyRepo: ${{ matrix.repo }}
          eventType: released
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
